# Generated by Django 3.1.7 on 2021-04-27 14:45

import direct.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=150, validators=[direct.models.val_subject])),
                ('first_message', models.CharField(max_length=250, validators=[direct.models.val_message])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, validators=[direct.models.val_message])),
                ('is_staff', models.BooleanField(default=False)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direct.chatmodel')),
            ],
        ),
    ]
