# Generated by Django 3.1.7 on 2021-04-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_chatmodel_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-message_time']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='msg_text',
        ),
    ]
