# Generated by Django 3.1.7 on 2021-04-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0004_auto_20210401_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bg_color',
        ),
    ]
